### ISSUE TITLE
CTL tag ignored?

### ISSUE THREAD

**Issue by juhavt** [drventure/Disambiguator#6]
Hi,

Thanks for this plugin, it's just what I was looking for!

However, I'm struggling to get it to work. I read the help file and followed it exactly but for some reason `ctl` tag isn't honored.

My test window title was `Windows security` and I used child control name which was unique but still all the entries matched. It seemed like the `ctl` tag was ignored.

I'm using the latest version of the plugin and Keepass on Windows 10.

In the log I'm getting the following:
```
27.8.2023 19.07.39 MatchSequence winName='Windows security{ctl:Enter your credentials to connect to*}'  sequence=''  eventId='1'  TargetTitle='Windows Security'  TargetHandle='18091642'
27.8.2023 19.07.39    Matching 'Windows Security' to 'Windows security' as pattern resulted in !!!MATCH!!!
27.8.2023 19.07.39    Sequence matched.
27.8.2023 19.07.39    Adding Sequence to found list

27.8.2023 19.07.39 MatchSequence winName='*{exe:POWERPNT.EXE}'  sequence=''  eventId='1'  TargetTitle='Windows Security'  TargetHandle='18091642'
27.8.2023 19.07.39    Matching 'Windows Security' to '*' as pattern resulted in !!!MATCH!!!
27.8.2023 19.07.39    Searching for EXE tag 'POWERPNT.EXE'
27.8.2023 19.07.39    Matching 'credentialuibroker.exe' to 'POWERPNT.EXE' as pattern resulted in no match
27.8.2023 19.07.39    Executable path 'c:\windows\system32\credentialuibroker.exe' did not match 'POWERPNT.EXE'
27.8.2023 19.07.39    Sequence did not match.
```

Both of the log entries should NOT have matched the current window and it seems that `exe` tag is working but the `ctl` is not.

Have I misunderstood the documentation?

**Comment by drventure** [comment]
Hi
Thanks for writing!

Something does look a little off here, I'm just not sure what.

In the first part of your log, since the Window title matched, it SHOULD have logged something like this in addition....

"Scanning control tree using ctlParam '{0}'" 

and then showed the controls that it detected in the window and whether any of them matched. But that doesn't appear to be the case.

I believe there was a prob with the 1.0.2 or 1.0.3 versions where it wouldn't traverse the control tree properly, so are you certain you've got the 1.0.4 version installed?

It looks like the EXE tag is working properly, in that it correctly logged that it grabbed the EXE name of then window and that it didn't match powerpoint.exe, so that appears to be working fine.

It looks like you're on track with your understanding of how it's supposed to work, though!


When I have issues like this, first thing I do is remove any {exe} or {ctl} tags and make sure that Keepass is displaying the proper "entry selector" window and that it's showing the multiple entries that all match the window you're autotyping into.

Then put them back in one at a time.

Let me know how that goes, and also make sure you've got the 1.0.4 version installed and compiled by keepass

**Comment by juhavt** [comment]
Hi Darin,

Thanks for your fast and kind reply. I'm sorry for my really late reply but I didn't have time to debug this sooner. Better late than never!

Good to know that I’ve understood the function of the Disambiguator correctly! This will be extremely useful plugin for my use when we get it to work like it should. I have over 400 entries with autotype so you can imagine I’m getting quite many false positive matches with autotype hotkey.


> I believe there was a prob with the 1.0.2 or 1.0.3 versions where it wouldn't traverse the control tree properly, so are you certain you've got the 1.0.4 version installed?


Yes, I’m absolutely certain (checked on Keepass plugin page). I used the 1.0.0.0 version for years because the auto update didn’t work for that version. I ended up recently on your github page and noticed there were multiple new versions. In fact, this was the first time I read the documentation thoroughly, so I haven’t noticed the ctl tag before (I really wish I had).


> In the first part of your log, since the Window title matched, it SHOULD have logged something like this in addition....
> "Scanning control tree using ctlParam '{0}'"
> and then showed the controls that it detected in the window and whether any of them matched. But that doesn't appear to be the case.


Yes, this is what I assumed the plugin should do. And it did it with the exe tag like you noticed.


> When I have issues like this, first thing I do is remove any {exe} or {ctl} tags and make sure that Keepass is displaying the proper "entry selector" window and that it's showing the multiple entries that all match the window you're autotyping into.
> 
> Then put them back in one at a time.
> 
> Let me know how that goes, and also make sure you've got the 1.0.4 version installed and compiled by keepass

I think it will be best if I first make a completely new database and start testing with it as I now have hundreds of entries so I can’t be sure I have removed all the tags. In fact, I’ve added “Disambiguator” tag to the entries which uses this plugin in case I need to find them but it’s possible I’ve forgotten some entries. Do you happen to know any method how I could find all the entries which have Disambiguator tags?

Well, I ended up installing Keepass portable and made sure not to use the same config file (i.e. completely fresh install of Keepass). I installed only the Disambiguator plugin and made two entries that uses the `ctl` tag with unique value. Unfortunately, I'm getting the exact same behavior i.e. the `ctl` tag is ignored and all entries match if the Window title matches.

Let me know if you need more info or logs!

**Comment by drventure** [comment]
It really sounds like you might be getting hit with a common problem for Disambiguator users, and that's that Keepass will ALWAYS match a window if the Window Title (defined in Keepass) matches.

A couple things to mention. The Disambiguator v1.0.4 contains a little more helpful ui elements. If you look under the TOOLS menu in keepass, you should see a DISAMBIGUATOR menu, with 3 items, Report, logging and help.

Report and logging each turn on those respective features, and turn them off.

The HELP item shows a passable built in help page.

When you define a KEEPASS entry, the TITLE field is always used as a match test. This is built into keepass and there's no way to turn that off.

So if that TITLE field happens to match on more than one keepass entry, both entries will be shown, regardless of CTL tag.

To counter this, edit your keepass entry titles to something that won't match but is still meaningful as a title. Maybe add an "off" character or something.

So, as an example, instead of 

"Quicken Password" as a keepass title, maybe make it "Quicken Application Password Window" or somesuch, something that likely won't match.

Then use the TARGET WINDOW field to specify the actual title you want to match with.

The approach of creating a new keepass DB with just a few entries to test with is spot it.  That's the best way to isolate things to know what's really happening.

Finally, with the UI menu options, its now A LOT easier to turn on reporting and logging. With 1.0.4, the reporting is improved as well, so that should help in diagnosing where things are going south.

As an example, when Quicken moved to "Quicken Classic" recently, I had to revisit my keepass enties, cause the old ones no longer worked. It took me an hour or so of playing around till I finally found the combination that works. So you're definitely not alone. :)

Capture the log and report for a round and attach them if you can. Of course please review the files first to make sure you're comfortable with doing so, although neither the report nor the logs should expose any actual keepass entry details, only exe filenames and control names etc.)

**Comment by juhavt** [comment]
Hi,

Thanks again for your prompt reply. I debugged further but it seems always ending in the same result - if the `Target Window` field contains the target window title it will match regardless of the `ctl` tag.

Here is the log entry that explains it:
```
16.10.2023 18.26.41 Sequence Queries Begin
16.10.2023 18.26.41 Traversing Control Tree...
16.10.2023 18.26.41 REPORT:    Application of current target window: "c:\windows\explorer.exe"
16.10.2023 18.26.41 REPORT:    TargetWindow: 52693680 Resolved: True
16.10.2023 18.26.41 REPORT:    WindowID: 
16.10.2023 18.26.41 REPORT:      Name  : Windows Security
16.10.2023 18.26.41 REPORT:      Class : Credential Dialog Xaml Host
16.10.2023 18.26.41 REPORT:       Child ID: 
16.10.2023 18.26.41 REPORT:         Name  : Windows Security
16.10.2023 18.26.41 REPORT:         Class : TextBlock
16.10.2023 18.26.41 REPORT:       Child ID: CloseButton
16.10.2023 18.26.41 REPORT:         Name  : Close
16.10.2023 18.26.41 REPORT:         Class : Button
16.10.2023 18.26.41 REPORT:       Child ID: 
16.10.2023 18.26.41 REPORT:         Name  : 
16.10.2023 18.26.41 REPORT:         Class : ScrollViewer
16.10.2023 18.26.41 REPORT:          Child ID: 
16.10.2023 18.26.41 REPORT:            Name  : Enter network credentials
16.10.2023 18.26.41 REPORT:            Class : TextBlock
16.10.2023 18.26.41 REPORT:          Child ID: 
16.10.2023 18.26.41 REPORT:            Name  : Enter your credentials to connect to: [censored]
16.10.2023 18.26.41 REPORT:            Class : TextBlock
16.10.2023 18.26.41 REPORT:          Child ID: EditField_1
16.10.2023 18.26.41 REPORT:            Name  : Username
16.10.2023 18.26.41 REPORT:            Class : TextBox
16.10.2023 18.26.41 REPORT:          Child ID: PasswordField_2
16.10.2023 18.26.41 REPORT:            Name  : Password
16.10.2023 18.26.41 REPORT:            Class : PasswordBox
16.10.2023 18.26.41 REPORT:          Child ID: CheckBoxField_13
16.10.2023 18.26.41 REPORT:            Name  : Remember my credentials
16.10.2023 18.26.41 REPORT:            Class : CheckBox
16.10.2023 18.26.41 REPORT:       Child ID: OkButton
16.10.2023 18.26.41 REPORT:         Name  : OK
16.10.2023 18.26.41 REPORT:         Class : Button
16.10.2023 18.26.41 REPORT:       Child ID: CancelButton
16.10.2023 18.26.41 REPORT:         Name  : Cancel
16.10.2023 18.26.41 REPORT:         Class : Button
16.10.2023 18.26.41 MatchSequence winName='Entry_1_donotmatchanythingelse'  sequence='{USERNAME}{TAB}{PASSWORD}{ENTER}'  eventId='7'  TargetTitle='Windows Security'  TargetHandle='52693680'
16.10.2023 18.26.41    Matching 'Windows Security' to 'Entry_1_donotmatchanythingelse' as pattern resulted in no match
16.10.2023 18.26.41    Window Title 'Windows Security' did not match
16.10.2023 18.26.41 MatchSequence winName='Windows Security{ctl:Authorisation required by*}'  sequence=''  eventId='7'  TargetTitle='Windows Security'  TargetHandle='52693680'
16.10.2023 18.26.41    Matching 'Windows Security' to 'Windows Security' as pattern resulted in !!!MATCH!!!
16.10.2023 18.26.41    Sequence matched.
16.10.2023 18.26.41    Adding Sequence to found list
16.10.2023 18.26.41 Finished AutoType_SequenceQuery
16.10.2023 18.26.41 MatchSequence winName='Entry_2_donotmatchanythingelse'  sequence='{USERNAME}{TAB}{PASSWORD}{ENTER}'  eventId='7'  TargetTitle='Windows Security'  TargetHandle='52693680'
16.10.2023 18.26.41    Matching 'Windows Security' to 'Entry_2_donotmatchanythingelse' as pattern resulted in no match
16.10.2023 18.26.41    Window Title 'Windows Security' did not match
16.10.2023 18.26.41 MatchSequence winName='Windows Security{ctl:Enter your credentials to connect to*}'  sequence=''  eventId='7'  TargetTitle='Windows Security'  TargetHandle='52693680'
16.10.2023 18.26.41    Matching 'Windows Security' to 'Windows Security' as pattern resulted in !!!MATCH!!!
16.10.2023 18.26.41    Sequence matched.
16.10.2023 18.26.41    Adding Sequence to found list
16.10.2023 18.26.41 Finished AutoType_SequenceQuery
16.10.2023 18.26.41 Sequence Queries Ended with 2 Matched Sequences. 
``` 

To get better understanding here is a screenshot of the entries:

![image](https://github.com/drventure/Disambiguator/assets/39801064/74294597-99a9-488e-b829-aef07e0c27e9)

It might be a little thing, but I just can't figure out why both of those entries match.

**Comment by drventure** [comment]
Hi
Well, you're not imagining things. I just tried a quick test using notepad and notepad++ (both windows will match on the title *notepad*

And, yes, it appears that the ctl tag is being ignored. Both windows are matching. I'm not sure exactly what's happening.

Let me do a little investigating and get back to you.

**Comment by drventure** [comment]
Hi
Found the issue. I've created a new release to address the problem. Thanks for bearing with me on this!

You should be able to use the plugin update checker to update. The new version is 1.0.5

Either that or just download the zip from the releases page here on github and copy the Disambiguator.plgx file into your keepass plugins folder and restart keepass.

**Comment by juhavt** [comment]
> Hi Found the issue. I've created a new release to address the problem. Thanks for bearing with me on this!

Awesome, thank you! I can confirm that version 1.0.5 traverses the control tree for the `ctl` tag correctly! I will start adding `ctl` tag to more entries and will report if I find issues.

In fact, I already noticed from the log that currently the plugin tries to match everything in the target window control tree. I mean, for example, these log entries:
```
17.10.2023 22.39.26    Scanning control tree using ctlParam 'ctl_tag'
17.10.2023 22.39.26    Matching 'TextBlock' to 'ctl_tag' as pattern resulted in no match
17.10.2023 22.39.26    Matching 'CloseButton' to 'ctl_tag' as pattern resulted in no match
17.10.2023 22.39.26    Matching 'Close' to 'ctl_tag' as pattern resulted in no match
17.10.2023 22.39.26    Matching 'Button' to 'ctl_tag' as pattern resulted in no match
17.10.2023 22.39.26    Matching 'ScrollViewer' to 'ctl_tag' as pattern resulted in no match
17.10.2023 22.39.26    Matching 'TextBlock' to 'ctl_tag' as pattern resulted in no match
17.10.2023 22.39.26    Matching 'EditField_1' to 'ctl_tag' as pattern resulted in no match
17.10.2023 22.39.26    Matching 'Username' to 'ctl_tag' as pattern resulted in no match
17.10.2023 22.39.26    Matching 'TextBox' to 'ctl_tag' as pattern resulted in no match
17.10.2023 22.39.26    Matching 'PasswordField_2' to 'ctl_tag' as pattern resulted in no match
17.10.2023 22.39.26    Matching 'Password' to 'ctl_tag' as pattern resulted in no match
17.10.2023 22.39.26    Matching 'PasswordBox' to 'ctl_tag' as pattern resulted in no match
17.10.2023 22.39.26    Matching 'CheckBoxField_13' to 'ctl_tag' as pattern resulted in no match
17.10.2023 22.39.26    Matching 'CheckBox' to 'ctl_tag' as pattern resulted in no match
17.10.2023 22.39.26    Matching 'OkButton' to 'ctl_tag' as pattern resulted in no match
17.10.2023 22.39.26    Matching 'OK' to 'ctl_tag' as pattern resulted in no match
17.10.2023 22.39.26    Matching 'Button' to 'ctl_tag' as pattern resulted in no match
17.10.2023 22.39.26    Matching 'CancelButton' to 'ctl_tag' as pattern resulted in no match
17.10.2023 22.39.26    Matching 'Cancel' to 'ctl_tag' as pattern resulted in no match
17.10.2023 22.39.26    Matching 'Button' to 'ctl_tag' as pattern resulted in no match
``` 
Does this mean that it tries literally match `OK` to `ctl_tag`? If yes, I think this should be avoided because it could cause unintended behavior. Maybe exclude those entries from the search in future releases?

> You should be able to use the plugin update checker to update. The new version is 1.0.5
> 
> Either that or just download the zip from the releases page here on github and copy the Disambiguator.plgx file into your keepass plugins folder and restart keepass.

In fact, I'm using Rookiestyle's excellent plugin [EarlyUpdateCheck](https://github.com/Rookiestyle/EarlyUpdateCheck) to auto-update all of my (too many) plugins and even the Keepass program. It has even native support for the Disambiguator plugin and it's quite easy to add other plugins to auto-update if those aren't yet supported natively.

**Comment by drventure** [comment]
Hi

Great! Glad to hear that resolved it.

> Does this mean that it tries literally match OK to ctl_tag? If yes, I think this should be avoided because it could cause unintended behavior. Maybe exclude those entries from the search in future releases?

Yes, the plugin as it stands drills down 2 levels (the parent window, then each child and each childs children).
I could have made the control tag more specific but I was trying to keep in the tradition of Keepass itself and keep things as simple as possible for people using it.

Since the whole idea is to disambiguate, I looked at it as "expose everything I can find for matching purposes", so users would have a wide array of options. Surely one of those options will be unique enough to uniquely ID the window.

I suppose I could filter out entries like OK, CANCEL, etc, But since I only drill down 2 levels, it doesn't really represent any performance hit, and, well, it'd be a bit of randomness deciding which to filter.

But, definitely something to keep in mind!

Thanks again for all your help running this down!
